### ISSUE TITLE
not-working on node7+on windows

### ISSUE THREAD

**Issue by jazzmn** [ww24/log4js-node-extend#3]
seems we are having Problems on node7 and node8 on Windows..
line and column numbers are missing:
[2017-05-16 13:49:33.412] [DEBUG] ABC - myLogMessage '(,:,:,)'

I tried to find out why it does not work anymore.. if we look at log4js-extend.js in line 10:
 trace = getTrace(log);

log is undefined..
but it's working on node6.9

**Comment by ww24** [comment]
Sorry, I knew that it not working on node v7.
Please send a pull request if you like.
thx :)

**Comment by PertapaCode** [comment]
fixed with PR https://github.com/ww24/log4js-node-extend/pull/4

**Comment by jazzmn** [comment]
thanks for informing.
But one more thing: the npm sources have not yet been updated. seems this version is only available on github which is not used if I do: "npm install"
maybe this could be solved if you increased the version number in package.json

**Comment by ww24** [comment]
Sorry, I forgot to publish npm package. I'll publish new version soon.

**Comment by jazzmn** [comment]
That would be great. Thank you.
